//
// Created by et028745 on 12/14/2023.
//

#ifndef GRAPH_PUZZLE_GAME_EMIRHANTANDOGAN_MAIN_H
#define GRAPH_PUZZLE_GAME_EMIRHANTANDOGAN_MAIN_H


class main {

};


#endif //GRAPH_PUZZLE_GAME_EMIRHANTANDOGAN_MAIN_H
